apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
  - name: signer
    releaseName: signer
    valuesFile: values.yaml
    repo: ../charts/