name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml

  docker:
    name: Build and Release Container Image
    uses: ./.github/workflows/docker.yml
    needs: [test]
    if: github.event_name != 'pull_request'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  binary:
    name: Build and Release Binary
    uses: ./.github/workflows/binary.yml
    needs: [test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    with:
      go_version: '1.25'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}