name: Cleanup 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Branch Container Image
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'signer'
          package-type: 'container'
          min-versions-to-keep: 0
          ignore-versions: |
            latest
            '^(0|[1-9]\\d*)\\.0\\.0$'

      - name: Delete Branch Helm Chart
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'charts/signer'
          package-type: 'container'
          min-versions-to-keep: 0
          ignore-versions: |
            0.0.0-latest
            '^(0|[1-9]\\d*)\\.0\\.0$'