name: Release Helm Chart

on:
  push:
    branches:
      - '**'
    tags:
      - 'chart-v*'
    paths:
      - 'charts/signer/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install YQ
        uses: action-stars/install-tool-from-github-release@v0.2.6
        with:
          github_token: ${{ github.token }}
          owner: mikefarah
          repository: yq
          extract: false
          filename_format: "{name}_{os}_{arch}"
          check_command: yq --version
          version: latest

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Chart Version
        working-directory: ./charts
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#chart-v}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            VERSION="0.0.0-latest"
            yq e -i '.image.tag = "latest"' signer/values.yaml
          else
            # Sanitize branch name for semver compatibility
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9-]/-/g')
            VERSION="0.0.0-branch-${BRANCH_NAME}"
          fi
          echo "Setting version to ${VERSION}"
          yq e -i ".version = \"${VERSION}\"" signer/Chart.yaml
          yq e -i ".appVersion = \"${VERSION}\"" signer/Chart.yaml
          cat signer/Chart.yaml

      - name: Package Chart
        working-directory: ./charts
        run: helm package signer

      - name: Push Chart
        working-directory: ./charts
        run: |
          export OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          for pkg in *.tgz; do
            if [ -f "$pkg" ]; then
              echo "Pushing ${pkg} to oci://ghcr.io/${OWNER_LC}/charts"
              helm push "${pkg}" "oci://ghcr.io/${OWNER_LC}/charts"
            fi
          done
